---
- hosts: all
  vars:
    application_dir: /Applications
    caskroom_dir: /usr/local/caskroom
    applications:
      # Comment out any apps that you do not want to install using a '#'
      - alfred
      - appcleaner
      - dropbox
      - firefox
      - google-chrome
      - harvest
      - java
      - skype
      - slack
      - spotify
      - things
      - lastfm
      - vlc
      - tinygrab
      - sequel-pro
      - sublime-text3
      - iterm2
      - mou
      - phpstorm
      - sourcetree
      - transmission
      - transmit
      - vagrant
      - virtualbox
      - minecraft
      - arq
      - subtitles
      - steam
    homebrew_apps:
      - ack
      - ant
      - bash
      - curl
      - git
      - htop
      - lynx
      - npm
      - vim
    git_config:
      - "push.default current"
      - "user.email 'oliverlorton@gmail.com'"
      - "user.name 'Oliver Lorton'"
    local_dev_hostname: oliver.dev
  tasks:
    - include: tasks/git.yml
    - include: tasks/dotfiles-symlink.yml
    - include: tasks/homebrew.yml
    - include: tasks/php-dev.yml
    - include: tasks/set-osx-defaults.yml